/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ModelType = IDL.Variant({
  'cnn' : IDL.Null,
  'regime' : IDL.Null,
  'portfolio' : IDL.Null,
  'lstm' : IDL.Null,
  'sentiment' : IDL.Null,
  'anomaly' : IDL.Null,
});
export const UUID = IDL.Text;
export const AssetClass = IDL.Variant({
  'etf' : IDL.Null,
  'forex' : IDL.Null,
  'crypto' : IDL.Null,
  'index' : IDL.Null,
  'equity' : IDL.Null,
  'commodity' : IDL.Null,
});
export const Time = IDL.Int;
export const OptionType = IDL.Variant({ 'put' : IDL.Null, 'call' : IDL.Null });
export const OptionSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const SignalType = IDL.Variant({
  'buy' : IDL.Null,
  'strongBuy' : IDL.Null,
  'sell' : IDL.Null,
  'neutral' : IDL.Null,
  'strongSell' : IDL.Null,
});
export const SignalTier = IDL.Variant({
  'highConfidence' : IDL.Null,
  'premiumElite' : IDL.Null,
  'standard' : IDL.Null,
});
export const AIReasoning = IDL.Record({
  'regime' : IDL.Text,
  'overallScore' : IDL.Float64,
  'sentimentScore' : IDL.Float64,
  'fiiFlow' : IDL.Float64,
  'volumeRatio' : IDL.Float64,
  'riskWarning' : IDL.Text,
  'lstmProbability' : IDL.Float64,
  'patternDetected' : IDL.Text,
  'signalTier' : SignalTier,
});
export const StrategyType = IDL.Variant({
  'scalping' : IDL.Null,
  'trendFollowing' : IDL.Null,
  'arbitrage' : IDL.Null,
  'meanReversion' : IDL.Null,
  'breakout' : IDL.Null,
  'marketMaking' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AlertChannel = IDL.Record({
  'smsEnabled' : IDL.Bool,
  'emailEnabled' : IDL.Bool,
  'telegramEnabled' : IDL.Bool,
  'telegramChatId' : IDL.Text,
  'whatsappEnabled' : IDL.Bool,
});
export const ModelStatus = IDL.Variant({
  'active' : IDL.Null,
  'disabled' : IDL.Null,
  'paused' : IDL.Null,
});
export const AIModel = IDL.Record({
  'status' : ModelStatus,
  'lastTrained' : Time,
  'name' : IDL.Text,
  'modelType' : ModelType,
  'modelId' : UUID,
  'accuracy' : IDL.Float64,
});
export const TradingStyle = IDL.Variant({
  'positional' : IDL.Null,
  'swing' : IDL.Null,
  'intraday' : IDL.Null,
});
export const MasterTrader = IDL.Record({
  'traderId' : UUID,
  'name' : IDL.Text,
  'sharpeRatio' : IDL.Float64,
  'style' : TradingStyle,
  'monthlyFee' : IDL.Float64,
  'winRate' : IDL.Float64,
  'subscriberCount' : IDL.Nat,
  'maxDrawdown' : IDL.Float64,
  'totalReturnPct' : IDL.Float64,
});
export const StrategyConfig = IDL.Record({
  'id' : UUID,
  'riskSettings' : IDL.Record({
    'perTradeStopLossPct' : IDL.Float64,
    'positionSizePct' : IDL.Float64,
    'drawdownProtectionPct' : IDL.Float64,
    'maxPositions' : IDL.Nat,
    'dailyLossLimitPct' : IDL.Float64,
  }),
  'name' : IDL.Text,
  'parameters' : IDL.Text,
  'enabled' : IDL.Bool,
  'strategyType' : StrategyType,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'subscription' : IDL.Variant({
    'pro' : IDL.Null,
    'free' : IDL.Null,
    'elite' : IDL.Null,
  }),
  'createdAt' : Time,
  'role' : UserRole,
  'email' : IDL.Text,
  'kycStatus' : IDL.Variant({
    'verified' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'twoFaEnabled' : IDL.Bool,
  'phone' : IDL.Text,
});
export const Instrument = IDL.Record({
  'name' : IDL.Text,
  'exchange' : IDL.Text,
  'symbol' : IDL.Text,
  'assetClass' : AssetClass,
});
export const MarketHalt = IDL.Record({
  'startedAt' : Time,
  'expiresAt' : Time,
  'market' : IDL.Text,
  'reason' : IDL.Text,
});
export const MarketHoliday = IDL.Record({
  'date' : IDL.Text,
  'name' : IDL.Text,
  'market' : IDL.Text,
});
export const CopySubscription = IDL.Record({
  'maxCapital' : IDL.Float64,
  'masterId' : UUID,
  'copyCrypto' : IDL.Bool,
  'drawdownStopPct' : IDL.Float64,
  'copyRatioPct' : IDL.Float64,
  'copyEquity' : IDL.Bool,
  'copyFO' : IDL.Bool,
  'maxTradesPerDay' : IDL.Nat,
});
export const DailyReport = IDL.Record({
  'bestTrade' : IDL.Float64,
  'worstTrade' : IDL.Float64,
  'totalTrades' : IDL.Nat,
  'dayPnl' : IDL.Float64,
  'date' : IDL.Text,
  'losers' : IDL.Nat,
  'signalsAccuracy' : IDL.Float64,
  'winRate' : IDL.Float64,
  'winners' : IDL.Nat,
});
export const OptionPosition = IDL.Record({
  'id' : UUID,
  'iv' : IDL.Float64,
  'theta' : IDL.Float64,
  'strike' : IDL.Float64,
  'premium' : IDL.Float64,
  'userId' : IDL.Principal,
  'side' : OptionSide,
  'vega' : IDL.Float64,
  'underlying' : IDL.Text,
  'gamma' : IDL.Float64,
  'optionType' : OptionType,
  'quantity' : IDL.Float64,
  'expiry' : Time,
  'delta' : IDL.Float64,
});
export const OrderStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'filled' : IDL.Null,
  'rejected' : IDL.Null,
});
export const OrderSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const OrderType = IDL.Variant({
  'oco' : IDL.Null,
  'scaleOut' : IDL.Null,
  'iceberg' : IDL.Null,
  'cover' : IDL.Null,
  'twap' : IDL.Null,
  'vwap' : IDL.Null,
  'conditional' : IDL.Null,
  'scaleIn' : IDL.Null,
  'bracket' : IDL.Null,
  'smartEntry' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : UUID,
  'status' : OrderStatus,
  'brokerLatencyMs' : IDL.Opt(IDL.Nat),
  'slippagePct' : IDL.Opt(IDL.Float64),
  'userId' : IDL.Principal,
  'side' : OrderSide,
  'orderType' : OrderType,
  'filledAt' : IDL.Opt(Time),
  'target' : IDL.Opt(IDL.Float64),
  'stopLoss' : IDL.Opt(IDL.Float64),
  'instrumentSymbol' : IDL.Text,
  'placedAt' : Time,
  'quantity' : IDL.Float64,
  'limitPrice' : IDL.Opt(IDL.Float64),
  'slippageRs' : IDL.Opt(IDL.Float64),
  'condition' : IDL.Opt(IDL.Text),
});
export const PsychologyFlags = IDL.Record({
  'winRateHighVolumeDays' : IDL.Float64,
  'overTradingDetected' : IDL.Bool,
  'avgTradesAfterLoss' : IDL.Float64,
  'fomoDetected' : IDL.Bool,
  'revengeTradingDetected' : IDL.Bool,
});
export const BacktestResult = IDL.Record({
  'bestMonth' : IDL.Float64,
  'worstMonth' : IDL.Float64,
  'totalTrades' : IDL.Nat,
  'sharpeRatio' : IDL.Float64,
  'winRate' : IDL.Float64,
  'maxDrawdown' : IDL.Float64,
  'totalReturnPct' : IDL.Float64,
  'profitFactor' : IDL.Float64,
});
export const SavedStrategy = IDL.Record({
  'id' : UUID,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'backtestResults' : IDL.Opt(BacktestResult),
  'blocks' : IDL.Text,
});
export const PortfolioGreeks = IDL.Record({
  'totalTheta' : IDL.Float64,
  'totalVega' : IDL.Float64,
  'totalGamma' : IDL.Float64,
  'totalDelta' : IDL.Float64,
});
export const PositionSizingMethod = IDL.Variant({
  'atr' : IDL.Null,
  'volatility' : IDL.Null,
  'fixedPct' : IDL.Null,
  'kelly' : IDL.Null,
});
export const RiskLevel = IDL.Variant({
  'conservative' : IDL.Null,
  'aggressive' : IDL.Null,
  'moderate' : IDL.Null,
});
export const RiskProfile = IDL.Record({
  'paperModeForced' : IDL.Bool,
  'monthlyDrawdownLimitPct' : IDL.Float64,
  'weeklyLossLimitPct' : IDL.Float64,
  'tradingLocked' : IDL.Bool,
  'consecutiveLosses' : IDL.Nat,
  'maxPositions' : IDL.Nat,
  'positionSizingMethod' : PositionSizingMethod,
  'dailyLossLimitPct' : IDL.Float64,
  'riskLevel' : RiskLevel,
});
export const Signal = IDL.Record({
  'id' : UUID,
  'timeframe' : IDL.Text,
  'targetPrice' : IDL.Float64,
  'fundamentalScore' : IDL.Float64,
  'stopLoss' : IDL.Float64,
  'instrumentSymbol' : IDL.Text,
  'timestamp' : Time,
  'entryPrice' : IDL.Float64,
  'technicalScore' : IDL.Float64,
  'aiReasoning' : IDL.Opt(AIReasoning),
  'confidence' : IDL.Float64,
  'strategyName' : IDL.Text,
  'signalType' : SignalType,
});
export const PositionSide = IDL.Variant({
  'long' : IDL.Null,
  'short' : IDL.Null,
});
export const Trade = IDL.Record({
  'id' : UUID,
  'pnl' : IDL.Float64,
  'side' : PositionSide,
  'closedAt' : Time,
  'instrumentSymbol' : IDL.Text,
  'quantity' : IDL.Float64,
  'entryPrice' : IDL.Float64,
  'exitPrice' : IDL.Float64,
  'strategyName' : IDL.Text,
  'openedAt' : Time,
});
export const WatchlistItem = IDL.Record({
  'addedAt' : Time,
  'instrumentSymbol' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAIModel' : IDL.Func([IDL.Text, IDL.Float64, ModelType], [UUID], []),
  'addBrokerConnection' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [UUID], []),
  'addDailyReport' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'addInstrument' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, AssetClass],
      [],
      [],
    ),
  'addOptionPosition' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        Time,
        OptionType,
        OptionSide,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [UUID],
      [],
    ),
  'addSignal' : IDL.Func(
      [
        IDL.Text,
        SignalType,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(AIReasoning),
      ],
      [UUID],
      [],
    ),
  'addStrategy' : IDL.Func(
      [
        IDL.Text,
        StrategyType,
        IDL.Text,
        IDL.Record({
          'perTradeStopLossPct' : IDL.Float64,
          'positionSizePct' : IDL.Float64,
          'drawdownProtectionPct' : IDL.Float64,
          'maxPositions' : IDL.Nat,
          'dailyLossLimitPct' : IDL.Float64,
        }),
      ],
      [UUID],
      [],
    ),
  'addToWatchlist' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelOrder' : IDL.Func([UUID], [], []),
  'clearMarketHalt' : IDL.Func([IDL.Text], [], []),
  'deleteStrategy' : IDL.Func([UUID], [], []),
  'getAlertConfig' : IDL.Func([], [IDL.Opt(AlertChannel)], ['query']),
  'getAllAIModels' : IDL.Func([], [IDL.Vec(AIModel)], ['query']),
  'getAllMasterTraders' : IDL.Func([], [IDL.Vec(MasterTrader)], ['query']),
  'getAllStrategies' : IDL.Func([], [IDL.Vec(StrategyConfig)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInstrumentsByAssetClass' : IDL.Func(
      [AssetClass],
      [IDL.Vec(Instrument)],
      ['query'],
    ),
  'getMarketHalt' : IDL.Func([IDL.Text], [IDL.Opt(MarketHalt)], ['query']),
  'getMarketHolidays' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MarketHoliday)],
      ['query'],
    ),
  'getMyCopySubscriptions' : IDL.Func(
      [],
      [IDL.Vec(CopySubscription)],
      ['query'],
    ),
  'getMyDailyReports' : IDL.Func([], [IDL.Vec(DailyReport)], ['query']),
  'getMyOptionPositions' : IDL.Func([], [IDL.Vec(OptionPosition)], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getMyPsychologyFlags' : IDL.Func([], [IDL.Opt(PsychologyFlags)], ['query']),
  'getMySavedStrategies' : IDL.Func([], [IDL.Vec(SavedStrategy)], ['query']),
  'getPerformanceMetrics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalTrades' : IDL.Nat,
          'avgRR' : IDL.Float64,
          'totalPnl' : IDL.Float64,
          'winRate' : IDL.Float64,
          'maxDrawdown' : IDL.Float64,
          'profitFactor' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getPortfolioGreeks' : IDL.Func([], [PortfolioGreeks], ['query']),
  'getRiskProfile' : IDL.Func([], [IDL.Opt(RiskProfile)], ['query']),
  'getSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
  'getSignalsByInstrument' : IDL.Func([IDL.Text], [IDL.Vec(Signal)], ['query']),
  'getTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserPsychologyFlags' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PsychologyFlags)],
      ['query'],
    ),
  'getUserRiskProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(RiskProfile)],
      ['query'],
    ),
  'getWatchlist' : IDL.Func([], [IDL.Vec(WatchlistItem)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isMarketHalted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isMarketHoliday' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(MarketHoliday)],
      ['query'],
    ),
  'loadStrategy' : IDL.Func([UUID], [IDL.Opt(SavedStrategy)], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Text,
        OrderType,
        OrderSide,
        IDL.Float64,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
      ],
      [UUID],
      [],
    ),
  'registerMasterTrader' : IDL.Func(
      [
        IDL.Text,
        TradingStyle,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [UUID],
      [],
    ),
  'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveStrategy' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(BacktestResult)],
      [UUID],
      [],
    ),
  'setMarketHalt' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'subscribeToCopyTrading' : IDL.Func(
      [
        UUID,
        IDL.Float64,
        IDL.Float64,
        IDL.Nat,
        IDL.Float64,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'unsubscribeFromCopyTrading' : IDL.Func([UUID], [], []),
  'updateAIModelStatus' : IDL.Func([UUID, ModelStatus], [], []),
  'updateAlertConfig' : IDL.Func([AlertChannel], [], []),
  'updatePsychologyFlags' : IDL.Func([PsychologyFlags], [], []),
  'updateRiskProfile' : IDL.Func([RiskProfile], [], []),
  'upsertMarketHolidays' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(MarketHoliday)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ModelType = IDL.Variant({
    'cnn' : IDL.Null,
    'regime' : IDL.Null,
    'portfolio' : IDL.Null,
    'lstm' : IDL.Null,
    'sentiment' : IDL.Null,
    'anomaly' : IDL.Null,
  });
  const UUID = IDL.Text;
  const AssetClass = IDL.Variant({
    'etf' : IDL.Null,
    'forex' : IDL.Null,
    'crypto' : IDL.Null,
    'index' : IDL.Null,
    'equity' : IDL.Null,
    'commodity' : IDL.Null,
  });
  const Time = IDL.Int;
  const OptionType = IDL.Variant({ 'put' : IDL.Null, 'call' : IDL.Null });
  const OptionSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const SignalType = IDL.Variant({
    'buy' : IDL.Null,
    'strongBuy' : IDL.Null,
    'sell' : IDL.Null,
    'neutral' : IDL.Null,
    'strongSell' : IDL.Null,
  });
  const SignalTier = IDL.Variant({
    'highConfidence' : IDL.Null,
    'premiumElite' : IDL.Null,
    'standard' : IDL.Null,
  });
  const AIReasoning = IDL.Record({
    'regime' : IDL.Text,
    'overallScore' : IDL.Float64,
    'sentimentScore' : IDL.Float64,
    'fiiFlow' : IDL.Float64,
    'volumeRatio' : IDL.Float64,
    'riskWarning' : IDL.Text,
    'lstmProbability' : IDL.Float64,
    'patternDetected' : IDL.Text,
    'signalTier' : SignalTier,
  });
  const StrategyType = IDL.Variant({
    'scalping' : IDL.Null,
    'trendFollowing' : IDL.Null,
    'arbitrage' : IDL.Null,
    'meanReversion' : IDL.Null,
    'breakout' : IDL.Null,
    'marketMaking' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AlertChannel = IDL.Record({
    'smsEnabled' : IDL.Bool,
    'emailEnabled' : IDL.Bool,
    'telegramEnabled' : IDL.Bool,
    'telegramChatId' : IDL.Text,
    'whatsappEnabled' : IDL.Bool,
  });
  const ModelStatus = IDL.Variant({
    'active' : IDL.Null,
    'disabled' : IDL.Null,
    'paused' : IDL.Null,
  });
  const AIModel = IDL.Record({
    'status' : ModelStatus,
    'lastTrained' : Time,
    'name' : IDL.Text,
    'modelType' : ModelType,
    'modelId' : UUID,
    'accuracy' : IDL.Float64,
  });
  const TradingStyle = IDL.Variant({
    'positional' : IDL.Null,
    'swing' : IDL.Null,
    'intraday' : IDL.Null,
  });
  const MasterTrader = IDL.Record({
    'traderId' : UUID,
    'name' : IDL.Text,
    'sharpeRatio' : IDL.Float64,
    'style' : TradingStyle,
    'monthlyFee' : IDL.Float64,
    'winRate' : IDL.Float64,
    'subscriberCount' : IDL.Nat,
    'maxDrawdown' : IDL.Float64,
    'totalReturnPct' : IDL.Float64,
  });
  const StrategyConfig = IDL.Record({
    'id' : UUID,
    'riskSettings' : IDL.Record({
      'perTradeStopLossPct' : IDL.Float64,
      'positionSizePct' : IDL.Float64,
      'drawdownProtectionPct' : IDL.Float64,
      'maxPositions' : IDL.Nat,
      'dailyLossLimitPct' : IDL.Float64,
    }),
    'name' : IDL.Text,
    'parameters' : IDL.Text,
    'enabled' : IDL.Bool,
    'strategyType' : StrategyType,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'subscription' : IDL.Variant({
      'pro' : IDL.Null,
      'free' : IDL.Null,
      'elite' : IDL.Null,
    }),
    'createdAt' : Time,
    'role' : UserRole,
    'email' : IDL.Text,
    'kycStatus' : IDL.Variant({
      'verified' : IDL.Null,
      'pending' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'twoFaEnabled' : IDL.Bool,
    'phone' : IDL.Text,
  });
  const Instrument = IDL.Record({
    'name' : IDL.Text,
    'exchange' : IDL.Text,
    'symbol' : IDL.Text,
    'assetClass' : AssetClass,
  });
  const MarketHalt = IDL.Record({
    'startedAt' : Time,
    'expiresAt' : Time,
    'market' : IDL.Text,
    'reason' : IDL.Text,
  });
  const MarketHoliday = IDL.Record({
    'date' : IDL.Text,
    'name' : IDL.Text,
    'market' : IDL.Text,
  });
  const CopySubscription = IDL.Record({
    'maxCapital' : IDL.Float64,
    'masterId' : UUID,
    'copyCrypto' : IDL.Bool,
    'drawdownStopPct' : IDL.Float64,
    'copyRatioPct' : IDL.Float64,
    'copyEquity' : IDL.Bool,
    'copyFO' : IDL.Bool,
    'maxTradesPerDay' : IDL.Nat,
  });
  const DailyReport = IDL.Record({
    'bestTrade' : IDL.Float64,
    'worstTrade' : IDL.Float64,
    'totalTrades' : IDL.Nat,
    'dayPnl' : IDL.Float64,
    'date' : IDL.Text,
    'losers' : IDL.Nat,
    'signalsAccuracy' : IDL.Float64,
    'winRate' : IDL.Float64,
    'winners' : IDL.Nat,
  });
  const OptionPosition = IDL.Record({
    'id' : UUID,
    'iv' : IDL.Float64,
    'theta' : IDL.Float64,
    'strike' : IDL.Float64,
    'premium' : IDL.Float64,
    'userId' : IDL.Principal,
    'side' : OptionSide,
    'vega' : IDL.Float64,
    'underlying' : IDL.Text,
    'gamma' : IDL.Float64,
    'optionType' : OptionType,
    'quantity' : IDL.Float64,
    'expiry' : Time,
    'delta' : IDL.Float64,
  });
  const OrderStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'filled' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const OrderSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const OrderType = IDL.Variant({
    'oco' : IDL.Null,
    'scaleOut' : IDL.Null,
    'iceberg' : IDL.Null,
    'cover' : IDL.Null,
    'twap' : IDL.Null,
    'vwap' : IDL.Null,
    'conditional' : IDL.Null,
    'scaleIn' : IDL.Null,
    'bracket' : IDL.Null,
    'smartEntry' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : UUID,
    'status' : OrderStatus,
    'brokerLatencyMs' : IDL.Opt(IDL.Nat),
    'slippagePct' : IDL.Opt(IDL.Float64),
    'userId' : IDL.Principal,
    'side' : OrderSide,
    'orderType' : OrderType,
    'filledAt' : IDL.Opt(Time),
    'target' : IDL.Opt(IDL.Float64),
    'stopLoss' : IDL.Opt(IDL.Float64),
    'instrumentSymbol' : IDL.Text,
    'placedAt' : Time,
    'quantity' : IDL.Float64,
    'limitPrice' : IDL.Opt(IDL.Float64),
    'slippageRs' : IDL.Opt(IDL.Float64),
    'condition' : IDL.Opt(IDL.Text),
  });
  const PsychologyFlags = IDL.Record({
    'winRateHighVolumeDays' : IDL.Float64,
    'overTradingDetected' : IDL.Bool,
    'avgTradesAfterLoss' : IDL.Float64,
    'fomoDetected' : IDL.Bool,
    'revengeTradingDetected' : IDL.Bool,
  });
  const BacktestResult = IDL.Record({
    'bestMonth' : IDL.Float64,
    'worstMonth' : IDL.Float64,
    'totalTrades' : IDL.Nat,
    'sharpeRatio' : IDL.Float64,
    'winRate' : IDL.Float64,
    'maxDrawdown' : IDL.Float64,
    'totalReturnPct' : IDL.Float64,
    'profitFactor' : IDL.Float64,
  });
  const SavedStrategy = IDL.Record({
    'id' : UUID,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'backtestResults' : IDL.Opt(BacktestResult),
    'blocks' : IDL.Text,
  });
  const PortfolioGreeks = IDL.Record({
    'totalTheta' : IDL.Float64,
    'totalVega' : IDL.Float64,
    'totalGamma' : IDL.Float64,
    'totalDelta' : IDL.Float64,
  });
  const PositionSizingMethod = IDL.Variant({
    'atr' : IDL.Null,
    'volatility' : IDL.Null,
    'fixedPct' : IDL.Null,
    'kelly' : IDL.Null,
  });
  const RiskLevel = IDL.Variant({
    'conservative' : IDL.Null,
    'aggressive' : IDL.Null,
    'moderate' : IDL.Null,
  });
  const RiskProfile = IDL.Record({
    'paperModeForced' : IDL.Bool,
    'monthlyDrawdownLimitPct' : IDL.Float64,
    'weeklyLossLimitPct' : IDL.Float64,
    'tradingLocked' : IDL.Bool,
    'consecutiveLosses' : IDL.Nat,
    'maxPositions' : IDL.Nat,
    'positionSizingMethod' : PositionSizingMethod,
    'dailyLossLimitPct' : IDL.Float64,
    'riskLevel' : RiskLevel,
  });
  const Signal = IDL.Record({
    'id' : UUID,
    'timeframe' : IDL.Text,
    'targetPrice' : IDL.Float64,
    'fundamentalScore' : IDL.Float64,
    'stopLoss' : IDL.Float64,
    'instrumentSymbol' : IDL.Text,
    'timestamp' : Time,
    'entryPrice' : IDL.Float64,
    'technicalScore' : IDL.Float64,
    'aiReasoning' : IDL.Opt(AIReasoning),
    'confidence' : IDL.Float64,
    'strategyName' : IDL.Text,
    'signalType' : SignalType,
  });
  const PositionSide = IDL.Variant({ 'long' : IDL.Null, 'short' : IDL.Null });
  const Trade = IDL.Record({
    'id' : UUID,
    'pnl' : IDL.Float64,
    'side' : PositionSide,
    'closedAt' : Time,
    'instrumentSymbol' : IDL.Text,
    'quantity' : IDL.Float64,
    'entryPrice' : IDL.Float64,
    'exitPrice' : IDL.Float64,
    'strategyName' : IDL.Text,
    'openedAt' : Time,
  });
  const WatchlistItem = IDL.Record({
    'addedAt' : Time,
    'instrumentSymbol' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAIModel' : IDL.Func([IDL.Text, IDL.Float64, ModelType], [UUID], []),
    'addBrokerConnection' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [UUID],
        [],
      ),
    'addDailyReport' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'addInstrument' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, AssetClass],
        [],
        [],
      ),
    'addOptionPosition' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          Time,
          OptionType,
          OptionSide,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [UUID],
        [],
      ),
    'addSignal' : IDL.Func(
        [
          IDL.Text,
          SignalType,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(AIReasoning),
        ],
        [UUID],
        [],
      ),
    'addStrategy' : IDL.Func(
        [
          IDL.Text,
          StrategyType,
          IDL.Text,
          IDL.Record({
            'perTradeStopLossPct' : IDL.Float64,
            'positionSizePct' : IDL.Float64,
            'drawdownProtectionPct' : IDL.Float64,
            'maxPositions' : IDL.Nat,
            'dailyLossLimitPct' : IDL.Float64,
          }),
        ],
        [UUID],
        [],
      ),
    'addToWatchlist' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelOrder' : IDL.Func([UUID], [], []),
    'clearMarketHalt' : IDL.Func([IDL.Text], [], []),
    'deleteStrategy' : IDL.Func([UUID], [], []),
    'getAlertConfig' : IDL.Func([], [IDL.Opt(AlertChannel)], ['query']),
    'getAllAIModels' : IDL.Func([], [IDL.Vec(AIModel)], ['query']),
    'getAllMasterTraders' : IDL.Func([], [IDL.Vec(MasterTrader)], ['query']),
    'getAllStrategies' : IDL.Func([], [IDL.Vec(StrategyConfig)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInstrumentsByAssetClass' : IDL.Func(
        [AssetClass],
        [IDL.Vec(Instrument)],
        ['query'],
      ),
    'getMarketHalt' : IDL.Func([IDL.Text], [IDL.Opt(MarketHalt)], ['query']),
    'getMarketHolidays' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MarketHoliday)],
        ['query'],
      ),
    'getMyCopySubscriptions' : IDL.Func(
        [],
        [IDL.Vec(CopySubscription)],
        ['query'],
      ),
    'getMyDailyReports' : IDL.Func([], [IDL.Vec(DailyReport)], ['query']),
    'getMyOptionPositions' : IDL.Func([], [IDL.Vec(OptionPosition)], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getMyPsychologyFlags' : IDL.Func(
        [],
        [IDL.Opt(PsychologyFlags)],
        ['query'],
      ),
    'getMySavedStrategies' : IDL.Func([], [IDL.Vec(SavedStrategy)], ['query']),
    'getPerformanceMetrics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalTrades' : IDL.Nat,
            'avgRR' : IDL.Float64,
            'totalPnl' : IDL.Float64,
            'winRate' : IDL.Float64,
            'maxDrawdown' : IDL.Float64,
            'profitFactor' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getPortfolioGreeks' : IDL.Func([], [PortfolioGreeks], ['query']),
    'getRiskProfile' : IDL.Func([], [IDL.Opt(RiskProfile)], ['query']),
    'getSignals' : IDL.Func([], [IDL.Vec(Signal)], ['query']),
    'getSignalsByInstrument' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Signal)],
        ['query'],
      ),
    'getTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserPsychologyFlags' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PsychologyFlags)],
        ['query'],
      ),
    'getUserRiskProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(RiskProfile)],
        ['query'],
      ),
    'getWatchlist' : IDL.Func([], [IDL.Vec(WatchlistItem)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isMarketHalted' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isMarketHoliday' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(MarketHoliday)],
        ['query'],
      ),
    'loadStrategy' : IDL.Func([UUID], [IDL.Opt(SavedStrategy)], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Text,
          OrderType,
          OrderSide,
          IDL.Float64,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
        ],
        [UUID],
        [],
      ),
    'registerMasterTrader' : IDL.Func(
        [
          IDL.Text,
          TradingStyle,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [UUID],
        [],
      ),
    'removeFromWatchlist' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveStrategy' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(BacktestResult)],
        [UUID],
        [],
      ),
    'setMarketHalt' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'subscribeToCopyTrading' : IDL.Func(
        [
          UUID,
          IDL.Float64,
          IDL.Float64,
          IDL.Nat,
          IDL.Float64,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'unsubscribeFromCopyTrading' : IDL.Func([UUID], [], []),
    'updateAIModelStatus' : IDL.Func([UUID, ModelStatus], [], []),
    'updateAlertConfig' : IDL.Func([AlertChannel], [], []),
    'updatePsychologyFlags' : IDL.Func([PsychologyFlags], [], []),
    'updateRiskProfile' : IDL.Func([RiskProfile], [], []),
    'upsertMarketHolidays' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(MarketHoliday)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };