/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIModel {
  'status' : ModelStatus,
  'lastTrained' : Time,
  'name' : string,
  'modelType' : ModelType,
  'modelId' : UUID,
  'accuracy' : number,
}
export interface AIReasoning {
  'regime' : string,
  'overallScore' : number,
  'sentimentScore' : number,
  'fiiFlow' : number,
  'volumeRatio' : number,
  'riskWarning' : string,
  'lstmProbability' : number,
  'patternDetected' : string,
  'signalTier' : SignalTier,
}
export interface AlertChannel {
  'smsEnabled' : boolean,
  'emailEnabled' : boolean,
  'telegramEnabled' : boolean,
  'telegramChatId' : string,
  'whatsappEnabled' : boolean,
}
export type AssetClass = { 'etf' : null } |
  { 'forex' : null } |
  { 'crypto' : null } |
  { 'index' : null } |
  { 'equity' : null } |
  { 'commodity' : null };
export interface BacktestResult {
  'bestMonth' : number,
  'worstMonth' : number,
  'totalTrades' : bigint,
  'sharpeRatio' : number,
  'winRate' : number,
  'maxDrawdown' : number,
  'totalReturnPct' : number,
  'profitFactor' : number,
}
export interface CopySubscription {
  'maxCapital' : number,
  'masterId' : UUID,
  'copyCrypto' : boolean,
  'drawdownStopPct' : number,
  'copyRatioPct' : number,
  'copyEquity' : boolean,
  'copyFO' : boolean,
  'maxTradesPerDay' : bigint,
}
export interface DailyReport {
  'bestTrade' : number,
  'worstTrade' : number,
  'totalTrades' : bigint,
  'dayPnl' : number,
  'date' : string,
  'losers' : bigint,
  'signalsAccuracy' : number,
  'winRate' : number,
  'winners' : bigint,
}
export interface Instrument {
  'name' : string,
  'exchange' : string,
  'symbol' : string,
  'assetClass' : AssetClass,
}
export interface MarketHalt {
  'startedAt' : Time,
  'expiresAt' : Time,
  'market' : string,
  'reason' : string,
}
export interface MarketHoliday {
  'date' : string,
  'name' : string,
  'market' : string,
}
export interface MasterTrader {
  'traderId' : UUID,
  'name' : string,
  'sharpeRatio' : number,
  'style' : TradingStyle,
  'monthlyFee' : number,
  'winRate' : number,
  'subscriberCount' : bigint,
  'maxDrawdown' : number,
  'totalReturnPct' : number,
}
export type ModelStatus = { 'active' : null } |
  { 'disabled' : null } |
  { 'paused' : null };
export type ModelType = { 'cnn' : null } |
  { 'regime' : null } |
  { 'portfolio' : null } |
  { 'lstm' : null } |
  { 'sentiment' : null } |
  { 'anomaly' : null };
export interface OptionPosition {
  'id' : UUID,
  'iv' : number,
  'theta' : number,
  'strike' : number,
  'premium' : number,
  'userId' : Principal,
  'side' : OptionSide,
  'vega' : number,
  'underlying' : string,
  'gamma' : number,
  'optionType' : OptionType,
  'quantity' : number,
  'expiry' : Time,
  'delta' : number,
}
export type OptionSide = { 'buy' : null } |
  { 'sell' : null };
export type OptionType = { 'put' : null } |
  { 'call' : null };
export interface Order {
  'id' : UUID,
  'status' : OrderStatus,
  'brokerLatencyMs' : [] | [bigint],
  'slippagePct' : [] | [number],
  'userId' : Principal,
  'side' : OrderSide,
  'orderType' : OrderType,
  'filledAt' : [] | [Time],
  'target' : [] | [number],
  'stopLoss' : [] | [number],
  'instrumentSymbol' : string,
  'placedAt' : Time,
  'quantity' : number,
  'limitPrice' : [] | [number],
  'slippageRs' : [] | [number],
  'condition' : [] | [string],
}
export type OrderSide = { 'buy' : null } |
  { 'sell' : null };
export type OrderStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'filled' : null } |
  { 'rejected' : null };
export type OrderType = { 'oco' : null } |
  { 'scaleOut' : null } |
  { 'iceberg' : null } |
  { 'cover' : null } |
  { 'twap' : null } |
  { 'vwap' : null } |
  { 'conditional' : null } |
  { 'scaleIn' : null } |
  { 'bracket' : null } |
  { 'smartEntry' : null };
export interface PortfolioGreeks {
  'totalTheta' : number,
  'totalVega' : number,
  'totalGamma' : number,
  'totalDelta' : number,
}
export type PositionSide = { 'long' : null } |
  { 'short' : null };
export type PositionSizingMethod = { 'atr' : null } |
  { 'volatility' : null } |
  { 'fixedPct' : null } |
  { 'kelly' : null };
export interface PsychologyFlags {
  'winRateHighVolumeDays' : number,
  'overTradingDetected' : boolean,
  'avgTradesAfterLoss' : number,
  'fomoDetected' : boolean,
  'revengeTradingDetected' : boolean,
}
export type RiskLevel = { 'conservative' : null } |
  { 'aggressive' : null } |
  { 'moderate' : null };
export interface RiskProfile {
  'paperModeForced' : boolean,
  'monthlyDrawdownLimitPct' : number,
  'weeklyLossLimitPct' : number,
  'tradingLocked' : boolean,
  'consecutiveLosses' : bigint,
  'maxPositions' : bigint,
  'positionSizingMethod' : PositionSizingMethod,
  'dailyLossLimitPct' : number,
  'riskLevel' : RiskLevel,
}
export interface SavedStrategy {
  'id' : UUID,
  'userId' : Principal,
  'name' : string,
  'backtestResults' : [] | [BacktestResult],
  'blocks' : string,
}
export interface Signal {
  'id' : UUID,
  'timeframe' : string,
  'targetPrice' : number,
  'fundamentalScore' : number,
  'stopLoss' : number,
  'instrumentSymbol' : string,
  'timestamp' : Time,
  'entryPrice' : number,
  'technicalScore' : number,
  'aiReasoning' : [] | [AIReasoning],
  'confidence' : number,
  'strategyName' : string,
  'signalType' : SignalType,
}
export type SignalTier = { 'highConfidence' : null } |
  { 'premiumElite' : null } |
  { 'standard' : null };
export type SignalType = { 'buy' : null } |
  { 'strongBuy' : null } |
  { 'sell' : null } |
  { 'neutral' : null } |
  { 'strongSell' : null };
export interface StrategyConfig {
  'id' : UUID,
  'riskSettings' : {
    'perTradeStopLossPct' : number,
    'positionSizePct' : number,
    'drawdownProtectionPct' : number,
    'maxPositions' : bigint,
    'dailyLossLimitPct' : number,
  },
  'name' : string,
  'parameters' : string,
  'enabled' : boolean,
  'strategyType' : StrategyType,
}
export type StrategyType = { 'scalping' : null } |
  { 'trendFollowing' : null } |
  { 'arbitrage' : null } |
  { 'meanReversion' : null } |
  { 'breakout' : null } |
  { 'marketMaking' : null };
export type Time = bigint;
export interface Trade {
  'id' : UUID,
  'pnl' : number,
  'side' : PositionSide,
  'closedAt' : Time,
  'instrumentSymbol' : string,
  'quantity' : number,
  'entryPrice' : number,
  'exitPrice' : number,
  'strategyName' : string,
  'openedAt' : Time,
}
export type TradingStyle = { 'positional' : null } |
  { 'swing' : null } |
  { 'intraday' : null };
export type UUID = string;
export interface UserProfile {
  'username' : string,
  'subscription' : { 'pro' : null } |
    { 'free' : null } |
    { 'elite' : null },
  'createdAt' : Time,
  'role' : UserRole,
  'email' : string,
  'kycStatus' : { 'verified' : null } |
    { 'pending' : null } |
    { 'rejected' : null },
  'twoFaEnabled' : boolean,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WatchlistItem { 'addedAt' : Time, 'instrumentSymbol' : string }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAIModel' : ActorMethod<[string, number, ModelType], UUID>,
  'addBrokerConnection' : ActorMethod<[string, string, boolean], UUID>,
  'addDailyReport' : ActorMethod<
    [string, bigint, bigint, bigint, number, number, number, number, number],
    undefined
  >,
  'addInstrument' : ActorMethod<
    [string, string, string, AssetClass],
    undefined
  >,
  'addOptionPosition' : ActorMethod<
    [
      string,
      number,
      Time,
      OptionType,
      OptionSide,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
    ],
    UUID
  >,
  'addSignal' : ActorMethod<
    [
      string,
      SignalType,
      number,
      number,
      number,
      number,
      string,
      string,
      number,
      number,
      [] | [AIReasoning],
    ],
    UUID
  >,
  'addStrategy' : ActorMethod<
    [
      string,
      StrategyType,
      string,
      {
        'perTradeStopLossPct' : number,
        'positionSizePct' : number,
        'drawdownProtectionPct' : number,
        'maxPositions' : bigint,
        'dailyLossLimitPct' : number,
      },
    ],
    UUID
  >,
  'addToWatchlist' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelOrder' : ActorMethod<[UUID], undefined>,
  'clearMarketHalt' : ActorMethod<[string], undefined>,
  'deleteStrategy' : ActorMethod<[UUID], undefined>,
  'getAlertConfig' : ActorMethod<[], [] | [AlertChannel]>,
  'getAllAIModels' : ActorMethod<[], Array<AIModel>>,
  'getAllMasterTraders' : ActorMethod<[], Array<MasterTrader>>,
  'getAllStrategies' : ActorMethod<[], Array<StrategyConfig>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getInstrumentsByAssetClass' : ActorMethod<[AssetClass], Array<Instrument>>,
  'getMarketHalt' : ActorMethod<[string], [] | [MarketHalt]>,
  'getMarketHolidays' : ActorMethod<[string], Array<MarketHoliday>>,
  'getMyCopySubscriptions' : ActorMethod<[], Array<CopySubscription>>,
  'getMyDailyReports' : ActorMethod<[], Array<DailyReport>>,
  'getMyOptionPositions' : ActorMethod<[], Array<OptionPosition>>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getMyPsychologyFlags' : ActorMethod<[], [] | [PsychologyFlags]>,
  'getMySavedStrategies' : ActorMethod<[], Array<SavedStrategy>>,
  'getPerformanceMetrics' : ActorMethod<
    [],
    {
      'totalTrades' : bigint,
      'avgRR' : number,
      'totalPnl' : number,
      'winRate' : number,
      'maxDrawdown' : number,
      'profitFactor' : number,
    }
  >,
  'getPortfolioGreeks' : ActorMethod<[], PortfolioGreeks>,
  'getRiskProfile' : ActorMethod<[], [] | [RiskProfile]>,
  'getSignals' : ActorMethod<[], Array<Signal>>,
  'getSignalsByInstrument' : ActorMethod<[string], Array<Signal>>,
  'getTrades' : ActorMethod<[], Array<Trade>>,
  'getUserOrders' : ActorMethod<[Principal], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserPsychologyFlags' : ActorMethod<[Principal], [] | [PsychologyFlags]>,
  'getUserRiskProfile' : ActorMethod<[Principal], [] | [RiskProfile]>,
  'getWatchlist' : ActorMethod<[], Array<WatchlistItem>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isMarketHalted' : ActorMethod<[string], boolean>,
  'isMarketHoliday' : ActorMethod<[string, string], [] | [MarketHoliday]>,
  'loadStrategy' : ActorMethod<[UUID], [] | [SavedStrategy]>,
  'placeOrder' : ActorMethod<
    [
      string,
      OrderType,
      OrderSide,
      number,
      [] | [number],
      [] | [number],
      [] | [number],
      [] | [string],
    ],
    UUID
  >,
  'registerMasterTrader' : ActorMethod<
    [string, TradingStyle, number, number, number, number, number],
    UUID
  >,
  'removeFromWatchlist' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveStrategy' : ActorMethod<[string, string, [] | [BacktestResult]], UUID>,
  'setMarketHalt' : ActorMethod<[string, string, bigint], undefined>,
  'subscribeToCopyTrading' : ActorMethod<
    [UUID, number, number, bigint, number, boolean, boolean, boolean],
    undefined
  >,
  'unsubscribeFromCopyTrading' : ActorMethod<[UUID], undefined>,
  'updateAIModelStatus' : ActorMethod<[UUID, ModelStatus], undefined>,
  'updateAlertConfig' : ActorMethod<[AlertChannel], undefined>,
  'updatePsychologyFlags' : ActorMethod<[PsychologyFlags], undefined>,
  'updateRiskProfile' : ActorMethod<[RiskProfile], undefined>,
  'upsertMarketHolidays' : ActorMethod<
    [string, string, Array<MarketHoliday>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];